### ISSUE TITLE
Ability to specify directory to store music files

### ISSUE THREAD

**Issue by OneLastRun** [joyrider3774/PlayniteSound#50]
Not sure if it is required to have the location for the folder pull from the C drive but would love the ability to move the location of the music folder. I don't have the largest C drive and try to keep the number of files on it limited. I don't think the sounds folder would need to be reworked as there are only a handful of files that would be associated with that, but someone who has a rather large collection could take up a good amount of storage with song files. 

Keep up the great work.

**Comment by cnapolit** [comment]
Yeah, these files can get quite large en masse. Should be straight forward to allow different directories.

**Comment by cnapolit** [comment]
After some further thought, since this plugin shares it's data with the ExtraMetaDataLoader and that plugin has no plans of supporting something like this, it's probably best this feature isn't implemented.

I'd recommend creating a symbolic link instead: https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/create-symbolic-links
as a tl;dr, anything that would try to access the folder would get redirected to the target folder, while still keeping the expected path.

Let me know if this isn't feasible. Otherwise, I'll eventually close this item.
