### ISSUE TITLE
ScreenSaver compatibility

### ISSUE THREAD

**Issue by mikebarrett19** [joyrider3774/PlayniteSound#53]
When using PlayniteSound and enabling "Pause music when Playnite deactivates or minimizes", Playnite ScreenSaver will pause the music when starting. 
I'm not sure how viable it would be but I would love for music to continue to play when screensaver starts but still pausing when going to chrome or whatever. 
Maybe only pausing to non child processes?
Thanks!

**Comment by cnapolit** [comment]
This is more a ScreenSaver behavior issue rather than Sounds.
It's better imo that Sounds always listens went told to start/stop by other plugins/uri requests and those plugins regulate how they interact.
I have given a bit of thought for allowing control over the pausing behavior for ScreenSaver, so I'll try to expose that at some point.
I created a ticket for this feature here: https://github.com/cnapolit/ScreenSaver/issues/65

**Comment by mikebarrett19** [comment]
Oh makes sense. Thank you!
