### ISSUE TITLE
[Request] Automatically stop/start background music when it detects other music. 

### ISSUE THREAD

**Issue by limodual** [joyrider3774/PlayniteSound#55]
Background music should automatically stop when it detects music from the other sources either from the Playnite video's streaming or from outside the app or anywhere. When the other music get's stops, Background music should automatically resume, is this possible? It will be so useful for Playnite users who uses both Playnite Sound as well as Extra Meta Data extension where you can watch micro-trailers and videos for games within Playnite.

**Comment by cnapolit** [comment]
I haven't found anything in the brief searches online I've done that would allow the plugin to detect when other apps are playing audio.
The closest I could get is detecting when any audio is playing, but since that could be another app or even this very plugin, that's not very helpful.
The long-term solution with audio conflicts in app is to give control over to themes: https://github.com/joyrider3774/PlayniteSound/issues/40
At least then, if a theme is playing a trailer, it can control whether music is playing.

**Comment by limodual** [comment]
Sorry I should have not mentioned that it's very optional for Playnite music to detect other app's music and stop/start based on that because lot of users will use Playnite only without other apps, so it's kinda makes sense. But it will be very useful if the Playnite detects other music within itself and behave accordingly. Really looking forward for the Version 6 :)
