### ISSUE TITLE
Mute/Pause music when playing videos/trailers

### ISSUE THREAD

**Issue by Jambopaul** [joyrider3774/PlayniteSound#57]
It would be very convenient if the music would mute/pause/stop when videos embedded in the game descriptions (Steam Trailers, videos added via other plugins, etc) are playing (currently the music plays over the video audio) or at least the ability to quickly mute the music whenever we want, without going into the add-on settings to adjust the volume.

**Comment by cnapolit** [comment]
I haven't investigated behavior when playing a video using the built-in web browser, so I don't know what can be done for that.

However, I do have a solution to theme-controlled videos: https://github.com/joyrider3774/PlayniteSound/issues/40 .
It will give the theme control over music behavior. The plugin would control what file is used at that point.
The only caveat is the theme must explicitly support the plugin.

I know the main Playnite dev intends on adding a way for generic plugin support within themes, so that caveat may disappear eventually.
