### ISSUE TITLE
Plugin no longer downloading music from YouTube

### ISSUE THREAD

**Issue by Jambopaul** [joyrider3774/PlayniteSound#64]
As of the past few days, the plugin no longer downloads music from YouTube when I attempt to. I go through the UI and after selecting the song on YouTube, the download bar appears for a second and then it says "Done" but the music has not been downloaded or normalized. I double-checked to make sure that the FFMPEG directories were set properly, which they were, but it still refuses to download any music.  

Edit: I have attached my extensions log file in case it has information that helps at all.

[extensions.log](https://github.com/joyrider3774/PlayniteSound/files/11338324/extensions.log)

**Comment by cnapolit** [comment]
Someone else mentioned this in discord and I've recreated the behavior. My guess is something changed with Youtube.
I'll look into updating the library the plugin uses.

**Comment by Jambopaul** [comment]
How would I go about downloading and updating the library?

**Comment by cnapolit** [comment]
The problem is an issue with the version of YoutubeExplode the plugin uses. It's too stale at this point. No immediate solution right now, but I have a few things in mind.

In the mean time, You can add another download source that I just verified is still working. It's not enabled or even visible by default because reasons, but I use it plenty.
It grabs files from here: https://downloads.khinsider.com/

As with downloading anything, there's always the risk of malware, viruses, etc. I've never had any known issue with the files from the site and the person who runs it doesn't seem malicious from the brief conversation I had with them.

To do enable this source, exit Playnite & open the config file via this path within the installation folder "ExtensionsData\9c960604-b8bc-4407-a4e4-e291c6097c7d\config.json" and add a 1 to this field:
```json
"Downloaders": [
    2
  ]
```

So that it looks like this:
```json
"Downloaders": [
    1,
    2
  ]
```

You may see a bunch of 2s in there. That's just an embarrassing bug, feel free to get rid of them. They're mostly harmless.

Since there's no explicit support for this source, it will be the default option when auto-downloading & the plugin will only use Youtube as a backup. Since YouTube is busted, that doesn't really matter.

**Comment by robbely** [comment]
Is there a reason why YoutubeExplode can't simply be updated? (The latest version is only a few days old).

**Comment by cnapolit** [comment]
> Is there a reason why YoutubeExplode can't simply be updated? (The latest version is only a few days old).
Using the latest version causes a missing assembly exception to occur that requires code changes to handle.

The plugin is in a vastly different state right now than the release, so pushing out a fix isn't possible without creating a version of the plugin outside of the main branch.

I also need to understand just how often this error is being hit to minimize the time in which the plugin is ready to catch it.
If another module were to throw a similar error, the plugin could incidentally catch it and either mask the error or mishandle it.

This missing assembly exception was the main reason I couldn't use the latest version of the YoutubeExplode.
Now that I have a solution, updating the plugin with the latest version of YoutubeExplode can be done regularly;
not just when the feature stops working.

Also, since there is an alternative above, it's not completely as bad as having no capability at all.

**Comment by sauceysaucer** [comment]
Any new news on this? YouTube downloads still aren't working and the alternative site doesn't have every game soundtrack

**Comment by skylestia** [comment]
I'm having exactly the same symptoms. The addon will not download from Youtube, and if I use khinsider as suggested to download music for multiple games at a time, it gets stuck long before it's finished, with no error message or popup as far as I have seen

Edit: I just tried again and got the error "Unable to connect to remote server" after a few minutes

**Comment by robbely** [comment]
Why has this been closed? The issue is still there. Has this been abandoned?

**Comment by Jambopaul** [comment]
> Why has this been closed? The issue is still there. Has this been abandoned?

Not a dev on this add-on obviously, but it means that they have fixed the issue and when the next version comes out (Release 6.0), this fix will be implemented.

**Comment by cnapolit** [comment]
@Jambopaul thanks, pretty much exactly what's going on.

There is a feature I've been working on that was more work than I initially intended.
Not going to give any timelines, since I work on this when I have time/motivation.
Once the feature is in a good enough state, I will create some preview releases for this plugin until I feel comfortable rolling it out for everyone.
