### ISSUE TITLE
2 remaining bugs and 1 feature requested

### ISSUE THREAD

**Issue by WilliamLeGod** [joyrider3774/PlayniteSound#67]
Whats up bro! How are you doing?

I've been using Sound extension for so long now and until now there were some bugs but I tried to ignore them but now I couldn't bare anymore lol

If you still provide support on Sound extension, let me know, I would love to donate you to fix all the remaining bug to make it perfect extension!

I have sound On using wav file (gamestarted and gamestarting) and Music set per game

Here are the 3 issues I found so far:

1/ When exit a game and Playnite takes focus back, there is no music for the focused game unless I navigate to next game, music for the next game starts normally

2/ Waking Pc up from sleep with Playnite still running, when Playnite takes focus back, sound (all sound effects) lost no matter what I do unless restart Playnite and also there is no music for the focused game unless I navigate to next game, music for the next game starts normally BUT still NO sound
Issue 2 can only be fixed by unticking "Minimize after starting game" (Fullscreen mode) but this causes some issues and I don't want to untick it

3/ Is it possible to Mute sound right after Game starting trigger?

Sorry for the long chat but I'm really at a loss as I love your extension so much, it literally changes my gaming life!
I hope you could look into these when you have free time

Thanks in advanced!

**Comment by cnapolit** [comment]
> 1/ When exit a game and Playnite takes focus back, there is no music for the focused game unless I navigate to next game, music for the next game starts normally

Tried to recreate in fullscreen mode with a few configurations, but I'm not seeing the same behavior.
Windows implementation of focus from what I've heard is a bit buggy, so it could have something to do with it.
There are some general issues with the plugin regarding focus, but this one seems to be niche to your environment.

> 2/ Waking Pc up from sleep with Playnite still running, when Playnite takes focus back, sound (all sound effects) lost no matter what I do unless restart Playnite and also there is no music for the focused game unless I navigate to next game, music for the next game starts normally BUT still NO sound
Issue 2 can only be fixed by unticking "Minimize after starting game" (Fullscreen mode) but this causes some issues and I don't want to untick it

Are you sure this is the plugin? You even posted about it to the main app's github page here: https://github.com/JosefNemec/Playnite/issues/3495
I did see issues with Playnite's built-in audio, but that's unlikely to be related to the plugin.
I tried with & without that toggle, and the plugin seemed to behave as expected.
I'll re-attempt with some other sounds later, as I have most disabled.

> 3/ Is it possible to Mute sound right after Game starting trigger?

plugin settings -> Music -> Stop music when -> Game is starting

**Comment by WilliamLeGod** [comment]
Thanks for the quick reply

Regarding 3/ I would like to Mute Sound instead of Music as sound still trigger at game starting trigger as a bug for some themes specifically Ps5ish (related to game status event)

So it would be nice if u can add an option for Sound just like for Music trigger 

Thanks!

**Comment by cnapolit** [comment]
For any sound, deleting the corresponding file will prevent the sound from playing.
These files should be found in Extrametadata\default.
Next release will have explicit toggles.

**Comment by WilliamLeGod** [comment]
> For any sound, deleting the corresponding file will prevent the sound from playing.
> These files should be found in Extrametadata\default.
> Next release will have explicit toggles.

I already deleted them all but sound still trigger

**Comment by cnapolit** [comment]
Sorry for the extra late reply, but if the files aren't there, the plugin has nothing to play....
If the files are being recreated, that's a different story.

**Comment by cnapolit** [comment]
Closing due to age & multiple items being represented in the same ticket.
