### ISSUE TITLE
Stream music from Youtube or automate download

### ISSUE THREAD

**Issue by snackerfork** [joyrider3774/PlayniteSound#7]
I think it would be a great feature if, like the video trailer extension, there was some kind of way to either stream a track from the game's OST automatically and/or there was a way to automate downloading the file.

Ideally the extension would be able to search for "[game name] OST" and pull a song or a playlist from it, either the first song (like a query for "[game name] ost theme" or [game name] ost 1" or "[game name] ost main menu") or a randomly selected song (like, search "[game name] ost", collect the youtube links for the first X results, and then play one) and then play it in the background.

But if any of that is not possible, or as an alternative method, a way to more easily download a song would be great. The trailers extension uses youtubedl to download trailers and lets you pick one from a Youtube search query, which is then stored on the computer. If the extension could do something similar for a "[game name] OST" search, that would be fantastic.

**Comment by felipecustodio** [comment]
The Extra metadata tools extension would be a great starting point!

**Comment by joyrider3774** [comment]
this is out of the scope of the plugin, i won't add this sorry

**Comment by cnapolit** [comment]
@drnooooo @felipecustodio Just so you two know, work has been done to add automated downloading. One download source was fully implemented, but due to legal risks will not be making it into any official release.
I have a prototype for Youtube based on how extra metadata functions working at the moment for https://github.com/joyrider3774/PlayniteSound/issues/20, but it needs more time to add customization options and iron out kinks.
In terms of streaming music/audio, Sounds is currently designed around files, so streaming is out of the question for now.
Maybe some work could be done to have files that really just point to a Youtube video (i.e. File name: "Stream - Uncharted 2: Among Thieves Soundtrack - "Nate's Theme 2.0" (Main Theme)" file contents: "5-Z23q7ZLEU") and then we somehow load the audio directly into memory, but that's for the extreme long term.
However, this method would certainly brake with large enough videos and retrieving data in chunks sounds like too much work. Probably would just place a cap on songs of a certain length/size.
